title: "Assemblyline 4"
theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
color_scheme: "orange"
search_enabled: true
heading_anchors: true
logo: "/static/images/banner.svg"
# Aux links for the upper right navigation
aux_links:
  "Français":
    - "https://cybercentrecanada.github.io/assemblyline4_docs_fr/"

defaults:
  -
    scope:
      path: "_slides"  #__
    values:
      layout: "iframe"

collections:
  slides:
    output: true